tasks:
  - name: "Install dependencies"
    init: |
      echo "Starting installation of Solana" > ~/init-log.txt
      sh -c "$(curl -sSfL https://release.solana.com/v1.17.15/install)"
      echo "Installed Solana" > ~/init-log.txt
    command: |
      source ~/..bash_profile
      solana --version
