[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
evenswap = "8KswSMtEQ9sjHkZ7ogYy1e2wcnntFnCJigNijTFiQEfe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jordan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
